set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

  Plugin 'VundleVim/Vundle.vim'
  " Plugin 'tmux-plugins/vim-tmux-focus-events'
  Plugin 'tpope/vim-fugitive'
  Plugin 'junegunn/goyo.vim'
  Plugin 'mattn/webapi-vim'
  Plugin 'mattn/gist-vim'
  " Plugin 'mileszs/ack.vim'
  Plugin 'tpope/vim-obsession'
  Plugin 'tpope/vim-vividchalk'
  Plugin 'artanikin/vim-synthwave84'
  Plugin 'NLKNguyen/papercolor-theme'
  Plugin 'nanotech/jellybeans.vim'
  Plugin 'sainnhe/sonokai'
  Plugin 'sickill/vim-monokai'

  " Navigation
  Plugin 'christoomey/vim-tmux-navigator'
  Plugin 'ctrlpvim/ctrlp.vim'

  " ./install.py --clangd-completer --rust-completer --go-completer --ts-completer
  Plugin 'ycm-core/YouCompleteMe'
  Plugin 'vim-scripts/gtags.vim'
  Plugin 'rdnetto/YCM-Generator'

  " Plugin 'GNOME/devhelp', {'rtp': 'plugins/'}
  " Plugin 'tpope/vim-unimpaired'

  " Formating and editing
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-repeat'
  Plugin 'scrooloose/nerdcommenter'
  Plugin 'godlygeek/tabular'
  Plugin 'editorconfig/editorconfig-vim'
  " Plugin 'Raimondi/delimitMate'

  Plugin 'mattn/emmet-vim'
  Plugin 'embear/vim-localvimrc'

  " Plugin 'lervag/vimtex'

  " Plugin 'Rip-Rip/clang_complete'
  " Snipps
  " Plugin 'epilande/vim-es2015-snippets'
  Plugin 'SirVer/ultisnips'

  " Linting
  Plugin 'dense-analysis/ale'
  "
  " UI Plugins
  " Plugin 'vim-airline/vim-airline'
  " Plugin 'vim-airline/vim-airline-themes'
  " Plugin 'altercation/vim-colors-solarized'
  Plugin 'chriskempson/base16-vim'
  Plugin 'jdkanani/vim-material-theme'
  Plugin 'airblade/vim-gitgutter'

  Plugin 'preservim/nerdtree'
  Plugin 'ryanoasis/vim-devicons'
  " Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'
  Plugin 'majutsushi/tagbar'
  Plugin 'Shirk/vim-gas'


  " Syntax highlighting

  " Plugin 'bohlender/vim-smt2'
  " Plugin 'ElmCast/elm-vim'
  " Plugin 'rhysd/vim-llvm'
  " Plugin 'Shouqun/chromium-vim'
  " Plugin 'wakatime/vim-wakatime'
  " Plugin 'pangloss/vim-javascript'
  " Plugin 'maxmellon/vim-jsx-pretty'
  " Plugin 'styled-components/vim-styled-components'
  Plugin 'sheerun/vim-polyglot'
  "Plugin 'mxw/vim-jsx'
  "Plugin 'Yggdroot/indentLine'
  "Plugin 'bitc/vim-hdevtools'
call vundle#end()

set clipboard=unnamedplus
" noremap x "1x but im using x+p alot so..
set timeoutlen=1000 ttimeoutlen=0

" read inline per file config
set modeline

let g:devhelpSearch=1
let g:devhelpAssistant=1


let delimitMate_jump_expansion = 1

let g:localvimrc_ask = 0

" CTags search parent directories
" set tags=tags;/

" Set tmux window name to the current file edited!
" autocmd BufReadPost,FileReadPost,BufNewFile * call system("tmux rename-window " . expand("%"))


" let g:ycm_semantic_triggers = {
"      \ 'elm' : ['.'],
"      \}

" let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = '0'
" let g:ycm_clangd_binary_path = '/usr/bin/clangd'
" let g:ycm_min_num_of_chars_for_completion = 1337
let g:ycm_min_num_of_chars_for_completion = 4
" let g:ycm_filter_diagnostics = { 'javascript': { 'regex': [ '.*' ] } }
" let g:polyglot_disabled = ['elm', 'latex']
" let g:polyglot_disabled = ['elm', 'js', 'jsx']
let g:yats_host_keyword = 1
autocmd BufWinEnter quickfix set nowrap!

let g:clang_library_path='/usr/lib/llvm-7/lib'

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Sets how many lines of history VIM has to remember
set history=700

" Opening a new split will make all open splits equal w/h
set equalalways

" Enable filetype plugins
filetype plugin indent on

" Set to auto read when a file is changed from the outside
set autoread
autocmd FocusGained,BufEnter * silent! checktime

" Dont put temp junk in the file directory
set backupdir=~/.vim/backup,~/.vim/tmp
set directory=~/.vim/backup,~/.vim/tmp

" Enable mouse scrolling, clicks etc
set mouse=a

" Leader key mapping and timeout
nnoremap <Space> <Nop>
nnoremap j gj
nnoremap k gk
set timeoutlen=400
set ttimeoutlen=400
let mapleader = " "
nnoremap <Leader>e :e %:h/%:t:r.

set relativenumber

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" This allows buffers to be hidden if you've modified a buffer.
" This is almost a must if you wish to use buffers in this way.
set hidden

" To open a new empty buffer
" nmap <Leader>bb :enew<cr>

" nmap <M-j> <Plug>(ale_next_wrap)
" nmap <M-k> <Plug>(ale_previous_wrap)

" execute "set <M-h>=h"
" execute "set <M-l>=l"
" Move to the next buffer
nmap <S-l> :bnext<CR>

" Move to the previous buffer
nmap <S-h> :bprevious<CR>

execute "set <M-1>=1"
execute "set <M-2>=2"
execute "set <M-3>=3"
execute "set <M-4>=4"
execute "set <M-5>=5"
execute "set <M-6>=6"
execute "set <M-7>=7"
execute "set <M-8>=8"
execute "set <M-9>=9"
noremap <M-1> :b1<CR>
noremap <M-2> :b2<CR>
noremap <M-3> :b3<CR>
noremap <M-4> :b4<CR>
noremap <M-5> :b5<CR>
noremap <M-6> :b6<CR>
noremap <M-7> :b7<CR>
noremap <M-8> :b8<CR>
noremap <M-9> :b9<CR>

execute "set <M-r>=r"
nmap <M-r> :!gcc -o tmp.out % && ./tmp.out; echo "exit code: $?" && rm tmp.out<CR>

" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <Leader>x :bd<CR>

" Show all open buffers and their status
nnoremap gb :ls<CR>:buffer<Space>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Editing text
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Backspace removes everything on the line.
set backspace=eol,indent,start

" Linebreak on 120 characters
set lbr
set textwidth=80

" format paragraph
nnoremap <Leader>q gqap

" quickfix window
nnoremap <Leader>qo :copen 4<CR>
nnoremap <Leader>qc :cclose <CR>
nnoremap <Leader>] :cn<CR>
nnoremap <Leader>[ :cp<CR>

" Default indention style
set tabstop=4
set softtabstop=2
set shiftwidth=2
set expandtab "tab -> spaces. `C-V <Tab>` for normal tab
set shiftround "Round indent to nearest shiftwidth multiple
" set foldmethod=syntax

" nnoremap <leader>jd :ALEGoToDefinition<CR>
" nnoremap <leader>jf :ALEFindReferences<CR>

nnoremap <leader>jd :YcmCompleter GoTo<CR>
nnoremap <leader>jt :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>jr :YcmCompleter GoToReferences<CR>
nnoremap <leader>fi :YcmCompleter FixIt<CR>
" Makefiles need tabs
autocmd FileType make setlocal noexpandtab

" Tabularize macros
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => User interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Search while typing
set incsearch

noremap <Leader>l :set list!<CR> " Toggle invisible chars$"

" Open folded lines when searching
"set foldopen

" Toggle highlight search results
nnoremap <Leader>h :set hlsearch!<CR>

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7


if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
" if filereadable(expand("~/.vimrc_background"))
  " let base16colorspace=256
"   source ~/.vimrc_background
" endif

" set t_Co=256
set background=dark
" colorscheme material-theme
" colorscheme vividchalk
" colorscheme synthwave84
" colorscheme PaperColor
colorscheme jellybeans

"hi Normal ctermbg=none

" show row numbers
set number

" Don't wrap lines
set nowrap

" Use syntax highlighting
syntax on

" Show guide lines
autocmd WinLeave * set nocursorline nocursorcolumn
autocmd WinEnter * set cursorline cursorcolumn
" set cursorline cursorcolumn

" No annoying sound on errors
set noerrorbells
set novisualbell!
set t_vb=
set tm=500


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" -> indentLine
"let g:indentLine_char = '¦'
"let g:indentLine_color_term = 234
"let g:ale_fixers = {
"\   'javascript': [
"\       'eslint',
"\   ],
"\}
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier']
let g:ale_fixers['typescript'] = ['prettier']
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0

let g:ale_linters = {'c': [] }
let g:ale_linters = {'cpp': [] }

" let g:ale_completion_enabled = 1
" set omnifunc=ale#completion#OmniFunc
" let g:e_linters = {'c': 'gcc'}
" let g:ale_linters = {
" \   'javascript': ['eslint'],
" \}
let g:ale_javascript_eslint_executable='npx eslint'
let g:ale_fix_on_save = 1

let g:javascript_conceal_function             = "ƒ"
let g:javascript_conceal_null                 = "ø"
let g:javascript_conceal_this                 = "@"
let g:javascript_conceal_return               = "⇚"
let g:javascript_conceal_undefined            = "¿"
let g:javascript_conceal_NaN                  = "ℕ"
let g:javascript_conceal_prototype            = "¶"
let g:javascript_conceal_static               = "•"
let g:javascript_conceal_super                = "Ω"
let g:javascript_conceal_arrow_function       = "⇒"
let g:javascript_conceal_noarg_arrow_function = "🞅"
let g:javascript_conceal_underscore_arrow_function = "🞅"
set conceallevel=1
let g:javascript_plugin_jsdoc = 1
" -> ctrlp.vim
" Set ignore patterns
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\'

" Use command-t mapping
let g:ctrlp_map = '<Leader>t'
nnoremap <Leader>b :CtrlPBuffer<CR>

" -> vim-coffe-script
" Treat litcoffee as coffee
autocmd FileType litcoffee runtime ftplugin/coffee.vim
autocmd FileType sh set tw=0
" autocmd FileType ts   setfiletype typescript
autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript

" -> vim-airline
"
" let g:airline_theme='hybrid'

" Enable tab bar
" let g:airline#extensions#tabline#enabled = 1

" Show just the filename
" let g:airline#extensions#tabline#fnamemod = ':t'

" Enable powerline fonts
" let g:airline_powerline_fonts = 1

" Show status bar
set laststatus=2

:set ttymouse=xterm2

" -> NERDTree / NERDTreeTabs
" Open NERDTree in all tabs
let NERDTreeMinimalUI=1
nnoremap <Leader>n :NERDTreeToggle<CR>

" -> goyo.vim
" adjust magrins
let g:goyo_width = 80
let g:goyo_margin_top = 0
let g:goyo_margin_bottom = 0

" -> vim-gist
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1
let g:gist_post_private = 1

let g:UltiSnipsExpandTrigger="<c-x>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsSnippetsDir="~/.vim/UltiSnips"

let g:NERDTrimTrailingWhitespace = 1
let g:NERDUsePlaceHolders = 0
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'both'
let g:NERDCustomDelimiters = {
      \ 'wast': {'left': ';;', 'rightAlt': ';)', 'leftAlt': '(;'}
      \ }


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Navigation and window management
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Resize split
nnoremap <silent> <Leader>+ :exe "resize " . (winheight(0) * 3/2)<CR>
nnoremap <silent> <Leader>- :exe "resize " . (winheight(0) * 2/3)<CR>

" Equal split size
nnoremap <Leader>= <c-W>=

" Navigation to splits
nnoremap <c-j> <c-W>j
nnoremap <c-k> <c-W>k
nnoremap <c-h> <c-W>h
nnoremap <c-l> <c-W>l

" neovim ^H fix.
" https://github.com/neovim/neovim/issues/2048
if has('nvim')
  nmap <BS> <C-W>h
endif

" Switch CWD to the directory of the open buffer
map <Leader>cd :cd %:p:h<cr>:pwd<cr>

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" Remember info about open buffers on close
set viminfo^=%

nmap <F8> <Plug>(ale_detail)
nmap <F7> :YcmCompleter GetDoc<cr>
nmap <leader>f <plug>(YCMHover)
" execute "set <M-j>=j"
" execute "set <M-k>=k"
nmap <silent> <Leader>k <Plug>(ale_previous)
nmap <silent> <Leader>j <Plug>(ale_next)

autocmd WinEnter * if &previewwindow | set nowrap! | endif

" Open vimgrep and put the cursor in the right position
map <Leader>g :vimgrep // **<left><left><left><left>
" set wildignore=

" Next/prev result
nnoremap ]q :cnext<cr>
nnoremap [q :cprevious<cr>

" Autoclose preview scratch
autocmd CompleteDone * pclose

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Misc, marcros etc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Disable Ex mode
map Q <Nop>

" Reload vim config on save
autocmd! bufwritepost $MYVIMRC source %

" Save as root. crashes neovim
" command! WW execute ':silent w !sudo tee % > /dev/null' | edit! %

" Treat :Q as :q
command! Q q

" Quickly open config file
nmap <Leader>v :tabedit $MYVIMRC<CR>

" Search for visual selected section
vnoremap // "y/<C-R>"<CR>

" enable italic
set t_ZH=[3m
set t_ZR=[23m
highlight Comment cterm=italic
" highlight SpellBad cterm=underline guifg=red
" highlight SpellLocal cterm=underline guifg=orange
highlight SpellCap cterm=underline guifg=yellow
highlight SpellRare cterm=underline guifg=yellow

autocmd VimLeave * call system("xclip -o | xclip -selection c")
