export LANG=en_US.UTF-8
export ZSH=$HOME/.oh-my-zsh
export EDITOR=vim
export NVM_DIR="$HOME/.nvm"
export GOPATH="$HOME/code/golang"
export PYENV_ROOT="$HOME/.pyenv"
export MANPATH="$MANPATH:$HOME/manpages"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH" # take precedence over /usr/bin

export GPG_TTY=$(tty)
[ -r "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Begin added by argcomplete
# fpath=( $HOME/.local/lib/python3.13/site-packages/argcomplete/bash_completion.d "${fpath[@]}" )
# End added by argcomplete

# Per-OS then per-machine overrides. Linked by `make symlinks`; .local is
# gitignored and lives only on the machine that needs it.
[ -r "$HOME/.zshenv.$(uname -s)" ] && . "$HOME/.zshenv.$(uname -s)"
[ -r "$HOME/.zshenv.local" ] && . "$HOME/.zshenv.local"
