export LANG=en_US.UTF-8

export ZSH=$HOME/.oh-my-zsh
export EDITOR=vim
export NVM_DIR="$HOME/.nvm"
export GOPATH="$HOME/code/golang"
export PYENV_ROOT="$HOME/.pyenv"

export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$NIX_PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export ANDROID_SDK_ROOT="$HOME/GREEN_LAB/android-sdk"
export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"
