[font]
size=18

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"
